language: python
python:
    - "3.4"
before_install:
    - pip install nose coverage coveralls
script:
    - nosetests --with-coverage --cover-package=web_server --cover-erase
after_success:
    - coveralls
